/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ConexaoBD;
import controller.ConexaoException;
import controller.PosicaoCliente;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.ModeloTabela;
import model.Posicao;

/**
 *
 * @author User
 */
public final class TelaAjusteVenda extends javax.swing.JFrame {

    Posicao mod = new Posicao();
    PosicaoCliente control = new PosicaoCliente();
    ConexaoBD conex = new ConexaoBD();
    TelaVenda venda;
    /**
     * Creates new form TelaAjusteVenda
     */
    public TelaAjusteVenda() {
        initComponents();
        
    }
    
    public void adicionaLinha(Object[] objVendas) {
        try {
            preencherTabela(objVendas);

        } catch (ConexaoException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao selecionar dados. " + ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro " + ex);
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Erro NullPointer: " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAjusteVenda = new javax.swing.JTable();
        jLabelQtd = new javax.swing.JLabel();
        jTextFieldAjuste = new javax.swing.JTextField();
        jButtonConf = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTableAjusteVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Sub Produto", "Ativo", "Produto em Garantia", "Data Vencimento", "NET"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAjusteVenda.getTableHeader().setReorderingAllowed(false);
        jTableAjusteVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAjusteVendaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableAjusteVenda);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 30, 1070, 80);

        jLabelQtd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelQtd.setText("Ajuste %");
        getContentPane().add(jLabelQtd);
        jLabelQtd.setBounds(40, 140, 80, 50);
        getContentPane().add(jTextFieldAjuste);
        jTextFieldAjuste.setBounds(130, 150, 160, 40);

        jButtonConf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonConf.setText("Confirmar");
        jButtonConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConf);
        jButtonConf.setBounds(130, 200, 100, 40);

        jButtonCancel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonCancel.setText("Cancelar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancel);
        jButtonCancel.setBounds(130, 250, 100, 40);

        setSize(new java.awt.Dimension(1101, 362));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableAjusteVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAjusteVendaMouseClicked
        TelaAjusteCompra ajuste = new TelaAjusteCompra();
        ajuste.setVisible(true);
    }//GEN-LAST:event_jTableAjusteVendaMouseClicked

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfActionPerformed
        // Atualizar jTableAlocacao e armazenar os dados em algum lugar
        //Depois da confirmação de alocação, dados serão processados no banco.
        
    }//GEN-LAST:event_jButtonConfActionPerformed

  public void preencherTabela(Object[] objVendas) throws ConexaoException, ClassNotFoundException {
      ArrayList dados = new ArrayList();
      String[] colunas = new String[]{"Produto", "Sub Produto", "Ativo", "Produto em Garantia", "Data Vencimento", "NET"};
      
      dados.add(objVendas);              
        
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        jTableAjusteVenda.setModel(modelo);
        jTableAjusteVenda.getColumnModel().getColumn(0).setPreferredWidth(150);
        jTableAjusteVenda.getColumnModel().getColumn(0).setResizable(false);
        jTableAjusteVenda.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTableAjusteVenda.getColumnModel().getColumn(1).setResizable(false);
        jTableAjusteVenda.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableAjusteVenda.getColumnModel().getColumn(2).setResizable(false);
        jTableAjusteVenda.getColumnModel().getColumn(3).setPreferredWidth(150);
        jTableAjusteVenda.getColumnModel().getColumn(3).setResizable(false);
        jTableAjusteVenda.getColumnModel().getColumn(4).setPreferredWidth(150);
        jTableAjusteVenda.getColumnModel().getColumn(4).setResizable(false);
        jTableAjusteVenda.getColumnModel().getColumn(5).setPreferredWidth(150);
        jTableAjusteVenda.getColumnModel().getColumn(5).setResizable(false);

        jTableAjusteVenda.getTableHeader().setReorderingAllowed(false);
        jTableAjusteVenda.setAutoResizeMode(jTableAjusteVenda.AUTO_RESIZE_OFF);
        jTableAjusteVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAjusteVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAjusteVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAjusteVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAjusteVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAjusteVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonConf;
    private javax.swing.JLabel jLabelQtd;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAjusteVenda;
    private javax.swing.JTextField jTextFieldAjuste;
    // End of variables declaration//GEN-END:variables
}
