/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ConexaoBD;
import controller.ConexaoException;
import controller.PosicaoCliente;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.ModeloTabela;
import model.Posicao;

/**
 *
 * @author User
 */
public class TelaCompra extends javax.swing.JFrame {

    Posicao mod = new Posicao();
    PosicaoCliente control = new PosicaoCliente();
    ConexaoBD conex = new ConexaoBD();
    /**
     * Creates new form TelaDeVenda
     */
    public TelaCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxItem = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCompra = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuSair4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCompra4 = new javax.swing.JMenuItem();
        jVenda4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jConsulta4 = new javax.swing.JMenuItem();
        jAlocacao3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBoxItem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBoxItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< Selecione uma das opções >", "Renda Fixa Pós com liquidez (LFT, CDBs, Fundos DI, Poupança)", "Renda Fixa Pós sem liquidez (LC, LCIs, LCAs, CDB longo)", "Renda Fixa Pós Crédito Privado (sem FGC - CRI, CRA, Deb)", "Renda Fixa Pré com liquidez (LTNs, NTN-F)", "Renda Fixa Pré sem liquidez (CDBs, LCs)", "Renda Fixa Pré Crédito Privado (LF, Debentures)", "Renda Fixa IPCA com liquidez (NTN-B)", "Renda Fixa IPCA sem liquidez (CDBs, LCs)", "Renda Fixa IPCA Crédito Privado (CRI, CRA, Debentures)", "Multimercado Baixa Vol (até 1.5%)", "Multimercado Média Vol (de 1.5% até 4%)", "Multimercado Alta Vol (acima de 4%)", "Fundos Imobiliários", "Carteira de Ações", "Fundos Internacionas sem hedge", "Proteção (Seguro Vida)", "Carteira Offshore (FX)" }));
        jComboBoxItem.setToolTipText("Opções Compra");
        jComboBoxItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxItemActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxItem);
        jComboBoxItem.setBounds(250, 30, 385, 30);

        jTableCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableCompra.getTableHeader().setReorderingAllowed(false);
        jTableCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCompraMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCompra);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 210, 1120, 630);

        jMenu1.setText("Arquivo");

        jMenuSair4.setText("Sair");
        jMenuSair4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSair4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSair4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuste");

        jCompra4.setText("Compra");
        jCompra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCompra4ActionPerformed(evt);
            }
        });
        jMenu2.add(jCompra4);

        jVenda4.setText("Venda");
        jVenda4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVenda4ActionPerformed(evt);
            }
        });
        jMenu2.add(jVenda4);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Clientes");

        jConsulta4.setText("Consulta");
        jConsulta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsulta4ActionPerformed(evt);
            }
        });
        jMenu4.add(jConsulta4);

        jMenuBar1.add(jMenu4);

        jAlocacao3.setText("Menu");

        jMenuItem4.setText("Alocação");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jAlocacao3.add(jMenuItem4);

        jMenuBar1.add(jAlocacao3);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1149, 913));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSair4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSair4ActionPerformed
         int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?");
        if(sair == JOptionPane.YES_OPTION){
            dispose();
            //System.exit(0);
        }
    }//GEN-LAST:event_jMenuSair4ActionPerformed

    private void jCompra4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCompra4ActionPerformed
        TelaCompra telaCompra = new TelaCompra();
        telaCompra.setVisible(true);
    }//GEN-LAST:event_jCompra4ActionPerformed

    private void jVenda4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVenda4ActionPerformed
        TelaVenda telaVenda = new TelaVenda();
        telaVenda.setVisible(true);
    }//GEN-LAST:event_jVenda4ActionPerformed

    private void jConsulta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsulta4ActionPerformed
        TelaConsulta telaConsulta = new TelaConsulta();
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_jConsulta4ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        TelaPrincipal menu = new TelaPrincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jComboBoxItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxItemActionPerformed
        String[] mensagem = {"< Selecione uma das opções >",
            "Renda Fixa Pós com liquidez (LFT, CDBs, Fundos DI, Poupança)",
            "Renda Fixa Pós sem liquidez (LC, LCIs, LCAs, CDB longo)",
            "Renda Fixa Pós Crédito Privado (sem FGC - CRI, CRA, Deb)",
            "Renda Fixa Pré com liquidez (LTNs, NTN-F)",
            "Renda Fixa Pré sem liquidez (CDBs, LCs)",
            "Renda Fixa Pré Crédito Privado (LF, Debentures)",
            "Renda Fixa IPCA com liquidez (NTN-B)",
            "Renda Fixa IPCA sem liquidez (CDBs, LCs)",
            "Renda Fixa IPCA Crédito Privado (CRI, CRA, Debentures)",
            "Multimercado Baixa Vol (até 1.5%)",
            "Multimercado Média Vol (de 1.5% até 4%)",
            "Multimercado Alta Vol (acima de 4%)",
            "Fundos Imobiliários",
            "Carteira de Ações",
            "Fundos Internacionas sem hedge",
            "Proteção (Seguro Vida)",
            "Carteira Offshore (FX)"};

        if (jComboBoxItem.getSelectedItem() == mensagem[0]) {
            JOptionPane.showMessageDialog(null, "Selecione uma das opções.");
        } else if (jComboBoxItem.getSelectedItem() == mensagem[jComboBoxItem.getSelectedIndex()]) {
            try {

                preencherTabela("SELECT cat.produto, cat.sub_produto, cat.ativo, cat.emissor, cat.data_vencimento\n"
                    + "FROM alocacao.catalogo_op AS cat\n"
                    + "WHERE cat.classificacao = '" + mensagem[jComboBoxItem.getSelectedIndex()] + "'");

            } catch (ConexaoException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao selecionar dados. " + ex);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Erro " + ex);
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(null, "Erro: " + ex);
            }
        }
    }//GEN-LAST:event_jComboBoxItemActionPerformed

    private void jTableCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCompraMouseClicked
        TelaAjusteCompra ajuste = new TelaAjusteCompra();
        ajuste.setVisible(true);
    }//GEN-LAST:event_jTableCompraMouseClicked

    
    public void preencherTabela(String sql) throws ConexaoException, ClassNotFoundException {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Produto", "Sub Produto", "Ativo", "Emissor", "Data Vencimento"};

       try {
            conex.open();

            conex.executaSql(sql);

            conex.rs.first();
            do {
                Object[] tabela = new Object[]{conex.rs.getString("produto"), conex.rs.getString("sub_produto"),
                    conex.rs.getString("ativo"), conex.rs.getString("emissor"),
                    conex.rs.getString("data_vencimento"), 
                };
                dados.add(tabela);
            } while (conex.rs.next());

        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao obter dados.");
        }catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }finally{
            conex.close();
        }
        

        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        jTableCompra.setModel(modelo);
        jTableCompra.getColumnModel().getColumn(0).setPreferredWidth(110);
        jTableCompra.getColumnModel().getColumn(0).setResizable(false);
        jTableCompra.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableCompra.getColumnModel().getColumn(1).setResizable(false);
        jTableCompra.getColumnModel().getColumn(2).setPreferredWidth(250);
        jTableCompra.getColumnModel().getColumn(2).setResizable(false);
        jTableCompra.getColumnModel().getColumn(3).setPreferredWidth(250);
        jTableCompra.getColumnModel().getColumn(3).setResizable(false);
        jTableCompra.getColumnModel().getColumn(4).setPreferredWidth(110);
        jTableCompra.getColumnModel().getColumn(4).setResizable(false);
        jTableCompra.getTableHeader().setReorderingAllowed(false);
        jTableCompra.setAutoResizeMode(jTableCompra.AUTO_RESIZE_OFF);
        jTableCompra.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);


    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jAlocacao3;
    private javax.swing.JComboBox<String> jComboBoxItem;
    private javax.swing.JMenuItem jCompra4;
    private javax.swing.JMenuItem jConsulta4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuSair4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCompra;
    private javax.swing.JMenuItem jVenda4;
    // End of variables declaration//GEN-END:variables
}
