/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Beatriz.aurelio
 */
public class TelaAjusteVenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaAjusteVenda
     */
    public TelaAjusteVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFVenda = new javax.swing.JInternalFrame();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuSair5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jAtivo5 = new javax.swing.JMenuItem();
        jCompra5 = new javax.swing.JMenuItem();
        jVenda5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jConsulta5 = new javax.swing.JMenuItem();
        jAlocacao3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jFVenda.setVisible(true);
        jFVenda.getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jFVenda.getContentPane().add(jComboBox1);
        jComboBox1.setBounds(33, 87, 73, 24);

        jLabel1.setText("Vendas");
        jFVenda.getContentPane().add(jLabel1);
        jLabel1.setBounds(33, 55, 73, 26);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beatriz.aurelio\\Downloads\\InterfaceJava-master\\src\\images\\page.png")); // NOI18N
        jMenu1.setText("Arquivo");

        jMenuSair5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beatriz.aurelio\\Downloads\\InterfaceJava-master\\src\\images\\door_out.png")); // NOI18N
        jMenuSair5.setText("Sair");
        jMenuSair5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSair5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSair5);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beatriz.aurelio\\Downloads\\InterfaceJava-master\\src\\images\\wrench_orange.png")); // NOI18N
        jMenu2.setText("Ajuste");

        jAtivo5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beatriz.aurelio\\Downloads\\InterfaceJava-master\\src\\images\\user.png")); // NOI18N
        jAtivo5.setText("Ativos");
        jAtivo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAtivo5ActionPerformed(evt);
            }
        });
        jMenu2.add(jAtivo5);

        jCompra5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beatriz.aurelio\\Downloads\\InterfaceJava-master\\src\\images\\user_add.png")); // NOI18N
        jCompra5.setText("Compra");
        jCompra5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCompra5ActionPerformed(evt);
            }
        });
        jMenu2.add(jCompra5);

        jVenda5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beatriz.aurelio\\Downloads\\InterfaceJava-master\\src\\images\\user_delete.png")); // NOI18N
        jVenda5.setText("Venda");
        jVenda5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVenda5ActionPerformed(evt);
            }
        });
        jMenu2.add(jVenda5);

        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beatriz.aurelio\\Downloads\\InterfaceJava-master\\src\\images\\group.png")); // NOI18N
        jMenu4.setText("Clientes");

        jConsulta5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beatriz.aurelio\\Downloads\\InterfaceJava-master\\src\\images\\zoom.png")); // NOI18N
        jConsulta5.setText("Consulta");
        jConsulta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConsulta5ActionPerformed(evt);
            }
        });
        jMenu4.add(jConsulta5);

        jMenuBar1.add(jMenu4);

        jAlocacao3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beatriz.aurelio\\Downloads\\InterfaceJava-master\\src\\images\\information.png")); // NOI18N
        jAlocacao3.setText("Menu");

        jMenuItem5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Beatriz.aurelio\\Downloads\\InterfaceJava-master\\src\\images\\page.png")); // NOI18N
        jMenuItem5.setText("Alocação");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jAlocacao3.add(jMenuItem5);

        jMenuBar1.add(jAlocacao3);

        jFVenda.setJMenuBar(jMenuBar1);

        getContentPane().add(jFVenda);
        jFVenda.setBounds(0, 0, 860, 540);

        setSize(new java.awt.Dimension(871, 564));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMenuSair5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSair5ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuSair5ActionPerformed

    private void jAtivo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAtivo5ActionPerformed
       TelaAjusteAtivo telaAtivo = new TelaAjusteAtivo();
        telaAtivo.setVisible(true);
    }//GEN-LAST:event_jAtivo5ActionPerformed

    private void jCompra5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCompra5ActionPerformed
        TelaAjusteCompra telaCompra = new TelaAjusteCompra();
        telaCompra.setVisible(true);
    }//GEN-LAST:event_jCompra5ActionPerformed

    private void jVenda5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVenda5ActionPerformed
        TelaAjusteVenda telaVenda = new TelaAjusteVenda();
        telaVenda.setVisible(true);
    }//GEN-LAST:event_jVenda5ActionPerformed

    private void jConsulta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConsulta5ActionPerformed
        TelaConsulta telaConsulta = new TelaConsulta();
        telaConsulta.setVisible(true);
    }//GEN-LAST:event_jConsulta5ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        TelaPrincipal menu = new TelaPrincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAjusteVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAjusteVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAjusteVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAjusteVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAjusteVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jAlocacao3;
    private javax.swing.JMenuItem jAtivo5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenuItem jCompra5;
    private javax.swing.JMenuItem jConsulta5;
    private javax.swing.JInternalFrame jFVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuSair5;
    private javax.swing.JMenuItem jVenda5;
    // End of variables declaration//GEN-END:variables
}
