/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ConexaoBD;
import controller.ConexaoException;
import controller.PosicaoCliente;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.ModeloTabela;
import model.Posicao;

/**
 *
 * @author User
 */
public class TelaCompra extends javax.swing.JFrame {

    Posicao mod = new Posicao();
    PosicaoCliente control = new PosicaoCliente();
    ConexaoBD conex = new ConexaoBD();
    /**
     * Creates new form TelaDeVenda
     */
    public TelaCompra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxItem = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlocacao = new javax.swing.JTable();
        jButtonConfirm = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCompra = new javax.swing.JTable();
        txtFieldPesquisa = new javax.swing.JTextField();
        buttonPesquisa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenuItem();
        jAlocacao = new javax.swing.JMenu();
        jMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBoxItem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBoxItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< Selecione uma das opções >", "Renda Fixa Pós com liquidez (LFT, CDBs, Fundos DI, Poupança)", "Renda Fixa Pós sem liquidez (LC, LCIs, LCAs, CDB longo)", "Renda Fixa Pós Crédito Privado (sem FGC - CRI, CRA, Deb)", "Renda Fixa Pré com liquidez (LTNs, NTN-F)", "Renda Fixa Pré sem liquidez (CDBs, LCs)", "Renda Fixa Pré Crédito Privado (LF, Debentures)", "Renda Fixa IPCA com liquidez (NTN-B)", "Renda Fixa IPCA sem liquidez (CDBs, LCs)", "Renda Fixa IPCA Crédito Privado (CRI, CRA, Debentures)", "Multimercado Baixa Vol (até 1.5%)", "Multimercado Média Vol (de 1.5% até 4%)", "Multimercado Alta Vol (acima de 4%)", "Fundos Imobiliários", "Carteira de Ações", "Fundos Internacionas sem hedge", "Proteção (Seguro Vida)", "Carteira Offshore (FX)" }));
        jComboBoxItem.setToolTipText("Opções Compra");
        jComboBoxItem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxItemActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxItem);
        jComboBoxItem.setBounds(310, 30, 385, 30);

        jTableAlocacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alocação Atual %", "Sugestão para Perfil"
            }
        ));
        jScrollPane1.setViewportView(jTableAlocacao);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 270, 100);

        jButtonConfirm.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonConfirm.setText("Confirmar Alocação");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirm);
        jButtonConfirm.setBounds(20, 150, 140, 30);

        jTableCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableCompra);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 220, 950, 620);

        txtFieldPesquisa.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtFieldPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldPesquisa);
        txtFieldPesquisa.setBounds(810, 80, 140, 30);

        buttonPesquisa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        buttonPesquisa.setText("Pesquisa");
        buttonPesquisa.setMaximumSize(new java.awt.Dimension(100, 40));
        buttonPesquisa.setMinimumSize(new java.awt.Dimension(100, 40));
        buttonPesquisa.setPreferredSize(new java.awt.Dimension(90, 35));
        buttonPesquisa.setVerifyInputWhenFocusTarget(false);
        buttonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(buttonPesquisa);
        buttonPesquisa.setBounds(860, 120, 90, 35);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Emissor");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(900, 30, 50, 40);

        jMenu1.setText("Arquivo");

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSair);

        jMenuBar1.add(jMenu1);

        jAlocacao.setText("Menu");

        jMenuItem.setText("Alocação");
        jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActionPerformed(evt);
            }
        });
        jAlocacao.add(jMenuItem);

        jMenuBar1.add(jAlocacao);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(991, 913));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxItemActionPerformed
        String[] mensagem = {"< Selecione uma das opções >",
            "Renda Fixa Pós com liquidez (LFT, CDBs, Fundos DI, Poupança)",
            "Renda Fixa Pós sem liquidez (LC, LCIs, LCAs, CDB longo)",
            "Renda Fixa Pós Crédito Privado (sem FGC - CRI, CRA, Deb)",
            "Renda Fixa Pré com liquidez (LTNs, NTN-F)",
            "Renda Fixa Pré sem liquidez (CDBs, LCs)",
            "Renda Fixa Pré Crédito Privado (LF, Debentures)",
            "Renda Fixa IPCA com liquidez (NTN-B)",
            "Renda Fixa IPCA sem liquidez (CDBs, LCs)",
            "Renda Fixa IPCA Crédito Privado (CRI, CRA, Debentures)",
            "Multimercado Baixa Vol (até 1.5%)",
            "Multimercado Média Vol (de 1.5% até 4%)",
            "Multimercado Alta Vol (acima de 4%)",
            "Fundos Imobiliários",
            "Carteira de Ações",
            "Fundos Internacionas sem hedge",
            "Proteção (Seguro Vida)",
            "Carteira Offshore (FX)"};

        if (jComboBoxItem.getSelectedItem() == mensagem[0]) {
            JOptionPane.showMessageDialog(null, "Selecione uma das opções.");
        } else if (jComboBoxItem.getSelectedItem() == mensagem[jComboBoxItem.getSelectedIndex()]) {
            try {

                preencherTabela("SELECT cat.produto, cat.sub_produto, cat.ativo, cat.emissor, cat.data_vencimento\n"
                    + "FROM alocacao.catalogo_op AS cat\n"
                    + "WHERE cat.classificacao = '" + mensagem[jComboBoxItem.getSelectedIndex()] + "'");

            } catch (ConexaoException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao selecionar dados. " + ex);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Erro " + ex);
            } catch (NullPointerException ex) {
                JOptionPane.showMessageDialog(null, "Erro: " + ex);
            }
        }
    }//GEN-LAST:event_jComboBoxItemActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?");
        if(sair == JOptionPane.YES_OPTION){
            dispose();
            //System.exit(0);
        }
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActionPerformed
        TelaPrincipal menu = new TelaPrincipal();
        menu.setVisible(true);
    }//GEN-LAST:event_jMenuItemActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        // passar os dados para tela principal

    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void txtFieldPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPesquisaActionPerformed

    private void buttonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPesquisaActionPerformed

        mod.setPesquisa(txtFieldPesquisa.getText());

        TelaPrincipal principal= new TelaPrincipal();
        principal.setVisible(true);
    }//GEN-LAST:event_buttonPesquisaActionPerformed

    
    public void preencherTabela(String sql) throws ConexaoException, ClassNotFoundException {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"Produto", "Sub Produto", "Ativo", "Emissor", "Data Vencimento"};

       try {
            conex.open();

            conex.executaSql(sql);

            conex.rs.first();
            do {
                Object[] tabela = new Object[]{conex.rs.getString("produto"), conex.rs.getString("sub_produto"),
                    conex.rs.getString("ativo"), conex.rs.getString("emissor"),
                    conex.rs.getString("data_vencimento"), 
                };
                dados.add(tabela);
            } while (conex.rs.next());

        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao obter dados.");
        }catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }finally{
            conex.close();
        }
        

        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        jTableCompra.setModel(modelo);
        jTableCompra.getColumnModel().getColumn(0).setPreferredWidth(110);
        jTableCompra.getColumnModel().getColumn(0).setResizable(false);
        jTableCompra.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableCompra.getColumnModel().getColumn(1).setResizable(false);
        jTableCompra.getColumnModel().getColumn(2).setPreferredWidth(250);
        jTableCompra.getColumnModel().getColumn(2).setResizable(false);
        jTableCompra.getColumnModel().getColumn(3).setPreferredWidth(250);
        jTableCompra.getColumnModel().getColumn(3).setResizable(false);
        jTableCompra.getColumnModel().getColumn(4).setPreferredWidth(110);
        jTableCompra.getColumnModel().getColumn(4).setResizable(false);
        jTableCompra.getTableHeader().setReorderingAllowed(false);
        jTableCompra.setAutoResizeMode(jTableCompra.AUTO_RESIZE_OFF);
        jTableCompra.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);


    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPesquisa;
    private javax.swing.JMenu jAlocacao;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JComboBox<String> jComboBoxItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem;
    private javax.swing.JMenuItem jMenuSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableAlocacao;
    private javax.swing.JTable jTableCompra;
    private javax.swing.JTextField txtFieldPesquisa;
    // End of variables declaration//GEN-END:variables
}
